### ISSUE TITLE
monitor all namespaces by default

### ISSUE THREAD

**Issue by h35gao** [Appdynamics/appdynamics-operator#18]
Is there any way to monitor all namespaces without adding them to nsToMonitor? If not, this should be a new feature.. 
Maintaining a list of all namespaces in a cluster in the spec is quite inconvenient.

**Comment by juwit** [comment]
We'd like to have this feature too !

**Comment by buckner** [comment]
I see there's a `NsToMonitorExclude` config setting that's not documented in the readme. I tried specifying that without `NsToMonitor` hoping it might monitor all namespaces but the ones excluded, but it didn't.

**Comment by davepalmeruk** [comment]
Yes, I have a client who has asked about this feature too.

**Comment by h35gao** [comment]
The workaround we have right now is to have an extra ansible task before the actual deployment to retrieve all namespaces in a cluster then pass the result to the deployment task.

**Comment by gswallow** [comment]
It's been since February that this issue is open.  Any plans to address this?

**Comment by rajesh2531** [comment]
Yes we need this feature too. Its really inconvenient to add all namespaces required to be monitored in 'nsToMonitor' field.

**Comment by gswallow** [comment]
On the flipside, I no longer care :)  Ah the joy of consulting.

**Comment by tguerena** [comment]
Need to have this feature too.

**Comment by Sprakhar97** [comment]
You can set nsToMoniTorRegex= .* to monitor all the namespaces without specifying them
Use this property for matching regex

**Comment by harekal7** [comment]
We can set nsToMoniTorRegex= .* as mentioned above.
