### ISSUE TITLE
custom resource CamelCase: Clusteragent vs ClusterAgent 

### ISSUE THREAD

**Issue by klml** [Appdynamics/appdynamics-operator#2]
```
# oc create -f development/openshift-configs/playbooks/roles/install_appdynamics/customresourcedefinition/clusteragent.yaml 
error: unable to recognize "development/openshift-configs/playbooks/roles/install_appdynamics/customresourcedefinition/clusteragent.yaml": no matches for kind "ClusterAgent" in version "appdynamics.com/v1alpha1"
```
in [custom resource](https://github.com/Appdynamics/appdynamics-operator/blob/master/README.md#clusteragent-deployment) you have `kind: ClusterAgent` (CamelCase!) but in [cluster-agent-operator-openshift.yaml](https://github.com/Appdynamics/appdynamics-operator/blob/master/deploy/cluster-agent-operator-openshift.yaml#L8) you use ` kind: Clusteragent` (no camelcase) 

I set my  custom resource to no camlecase an it worked.

**Comment by sashaPM** [comment]
The docs are updated accordingly. It needs to be a lower case 'a'

**Comment by SomniVertix** [comment]
Just to add to this for anyone else seeing this error. You have to deploy the AppDynamics operator before you deploy the Agent: https://docs.appdynamics.com/display/PRO45/Deploy+the+AppDynamics+Operator+on+Kubernetes 

Something that my tired eyes missed :joy:
