### ISSUE TITLE
metadata.name: "K8s-Cluster-Agent" needs a DNS-1123 subdomain formatting.

### ISSUE THREAD

**Issue by klml** [Appdynamics/appdynamics-operator#3]
Creating my customresourcedefinition, I get this:
 
```
# oc create -f development/openshift-configs/playbooks/roles/install_appdynamics/customresourcedefinition/clusteragent.yaml 
The Clusteragent "K8s-Cluster-Agent.appdynamics.com" is invalid: metadata.name: Invalid value: "K8s-Cluster-Agent": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
I changed `name: K8s-Cluster-Agent`  in [ClusterAgent deployment](https://github.com/Appdynamics/appdynamics-operator/blob/master/README.md#clusteragent-deployment) to `name: cluster-agent.appdynamics.com` and it worked, initially.

```
# oc create -f development/openshift-configs/playbooks/roles/install_appdynamics/customresourcedefinition/clusteragent.yaml 
clusteragent.appdynamics.com "cluster-agent.appdynamics.com" created
```

Furthermore I got another error in my running pod and I had to change the value to  `name: clusteragent`

**Comment by harekal7** [comment]
The custom resource name can be anything. The issue was due to a violation of the naming conventions in the custom resource definition.
